# The name of the environment matching the repository name
name: hip-hop-heuristics
# I prefer conda-forge packages for my projects
channels:
  - conda-forge
  - anaconda
  - hcc
# Start with Python` and include everything you need
dependencies:
  - bokeh
  - elasticsearch
  - jupyter
  - lxml
  - pandas
  - psycopg2
  - python=3.6
  - scikit-learn
  - spacy
  - statsmodels
  - tensorflow
