version: '3.1'
services:
  3h-arangodb:
    image: arangodb:3.4
    restart: always
    ports:
      - 8529:8529
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - /Volumes/MaxData/HipHopHeuristics/arangodb:/var/lib/arangodb3
      - /Volumes/MaxData/HipHopHeuristics/raw:/mnt/data
